site_name: Ultralytics YOLOv8 Docs
repo_url: https://github.com/ultralytics/ultralytics
edit_uri: https://github.com/ultralytics/ultralytics/tree/main/docs
repo_name: ultralytics/ultralytics

theme:
  name: "material"
  logo: https://github.com/ultralytics/assets/raw/main/logo/Ultralytics-logomark-white.png
  favicon: https://github.com/ultralytics/assets/raw/main/logo/favicon-yolo.ico
  font:
    text: Roboto

  palette:
    # Palette toggle for light mode
    - scheme: default
      # primary: grey
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      # primary: black
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - content.action.edit
    - content.code.annotate
    - content.tooltips
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    - navigation.top
    - navigation.expand
    - navigation.footer
    - content.tabs.link  # all code tabs change simultaneously

# Version drop-down menu
# extra:
#   version:
#     provider: mike

extra_css:
  - stylesheets/style.css

markdown_extensions:
  # Div text decorators
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - tables
  - attr_list
  - def_list
  # Syntax highlight
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets

  # Button
  - attr_list

  # Content tabs
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true

  # Highlight
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde

plugins:
  - mkdocstrings
  - search

# Primary navigation
nav:
  - Home: index.md
  - Quickstart: quickstart.md
  - Tasks:
      - Detection: tasks/detection.md
      - Segmentation: tasks/segmentation.md
      - Classification: tasks/classification.md
  - Usage:
      - CLI: cli.md
      - Python: python.md
      - Predict: predict.md
      - Configuration: cfg.md
      - Customization Guide: engine.md
  - Ultralytics HUB: hub.md
  - iOS and Android App: app.md
  - Reference:
      - Engine:
          - Model: reference/model.md
          - Trainer: reference/base_trainer.md
          - Validator: reference/base_val.md
          - Predictor: reference/base_pred.md
          - Exporter: reference/exporter.md
          - Results: reference/results.md
      - ultralytics.nn: reference/nn.md
      - Operations: reference/ops.md
